export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const RESET_USER = "RESET_USER";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const UPLOAD_AVATAR_REQUEST = "UPLOAD_AVATAR_REQUEST";
export const UPLOAD_AVATAR_FAIL = "UPLOAD_AVATAR_FAIL";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const GET_USER_BY_RESET_TOKEN = "GET_USER_BY_RESET_TOKEN";
export const GET_USER_BY_RESET_TOKEN_REQUEST =
  "GET_USER_BY_RESET_TOKEN_REQUEST";
export const GET_USER_BY_RESET_TOKEN_FAIL = "GET_USER_BY_RESET_TOKEN_FAIL";
