export const GET_ALL_COMMENTS_BY_PRODUCTS = "GET_ALL_COMMENTS_BY_PRODUCTS";
export const GET_ALL_COMMENTS_BY_PRODUCTS_REQUEST =
  "GET_ALL_COMMENTS_BY_PRODUCTS_REQUEST";
export const GET_ALL_COMMENTS_BY_PRODUCTS_FAIL =
  "GET_ALL_COMMENTS_BY_PRODUCTS_FAIL ";

export const RESET_COMMENT = "RESET_COMMENT";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const REPLY_COMMENT = "REPLY_COMMENT";
export const REPLY_COMMENT_REQUEST = "REPLY_COMMENT_REQUEST";
export const REPLY_COMMENT_FAIL = "REPLY_COMMENT_FAIL";
